global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: vueprom
    static_configs:
      - targets:
          - vueprom:8080

  - job_name: goveeprom
    static_configs:
      - targets:
          - goveeprom:8081
